[profile.default]
src = "src"
out = "out"
libs = []
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "contracts/=src/contracts/",
  "@openzeppelin/contracts-v5.2=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-v4.4=lib/contracts-v4.4",
  "forge-std=lib/forge-std/src"
]
