[profile.default]
src = "src"
out = "out"
libraries = []
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/contracts-v5.2=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-v4.4=src/contracts/@openzeppelin/contracts-v4.4",
    "forge-std=lib/forge-std/src",
    "contracts/=src/contracts/",
    "lido-v3/=src/contracts/"
]

[profile.default.extended_storage_layout]
run = false
